In [1]:
import numpy as np

section1:
3x + 5y = 6
7x - 5y = 9

```
[3  5]  [6]
[7 -5]  [9]
```

In [10]:
A = np.array([[3, 5], [7, -5]])
B = np.array([6, 9])
X = np.linalg.inv(A).dot(B)

print(X)

[1.5 0.3]


section2:
x + y + z = 6
    y + z = -4
2x + 5y - z = 27

```
[1  1  1]  [ 6 ]
[0 -1  1]  [-4 ]
[2  5 -1]  [ 27]
```

In [6]:
A = np.array([[1, 1, 1], [0, -1, 1],[2, 5, -1]])
B = np.array([6, -4, 27])
F = np.linalg.inv(A).dot(B)

print(F)

[-3.60287970e+16  1.80143985e+16  1.80143985e+16]


section3:
x + y = 4
2x + 2y = 8

```
[1  1]  [4]
[2  2]  [8]
```

In [14]:
A = np.array([[1, 1], [2, 2.00000000001]])
B = np.array([4, 8])
D = np.linalg.inv(A).dot(B)

print(D)

[4. 0.]
